# Generated by Django 4.1.4 on 2022-12-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0004_tb_balanco_delete_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_balanco',
            name='familia',
            field=models.CharField(max_length=50, verbose_name='Familia'),
        ),
        migrations.AlterModelTable(
            name='tb_balanco',
            table='paginas_tb_balanco',
        ),
    ]
